- ndsl/dsl/dace/wrapped_halo_exchange.py
- ndsl/grid/eta.py
- ndsl/stencils/c2l_ord.py
Dependency in  is due to the workaround for halo exchanged for `DaCe`, nicknamed `WrappedHaloUpdater`. This workaround demands we pass a reference to `state` instead of the variable directly.
Remove the type hint, verbose why and to enhance potential errors check for the required `u` and `v` in the `state`
`compute_eta` was in `pyFV3` but is required for grid calculations
Move down all components required to `ndsl`. Then refactor `pyFV3` to rely on them (TBD)
> [fix] Break pyFV3 dependency

- .github/workflows/lint.yaml
- .github/workflows/unit_tests.yaml
- .gitignore
GT4Py is looking into deprecating 3.8/3.9. In the interim of a decision, we begin the process to test for newer versions of Python.
> Add 3.11.7 to python in unit tests

- ndsl/dsl/dace/dace_config.py
- ndsl/dsl/typing.py
When asked for 32 bit float, we flip the DaCe default type to be a `f32`
> [Fix] f32 scalars in DaCe

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support_request.md
- .github/PULL_REQUEST_TEMPLATE.md
We merged PRs directly into `main` by mistake. Correcting this.
@fmalatino Data named has changed on the datashare which leads to ci breakage. Please force merge this and I will PR a fix to the ci to develop next
NB: we need to switch the `default` branch to `develop`
> [Branch fix] Merging `main` back in `develop`

- README.md
- setup.py
Update readme with CI badges & default py version
Update version of package to released version
No-op
**Checklist:**
> Update readme with CI badges & default py version

- ndsl/stencils/__init__.py
Changes to the import methods to avoid circular imports
Fixes # (issue)
This is a hotfix to v.2024.03.00
Tested via lint and currently implemented translate tests
OS: RHEL 8.9 Ootpa
Built conda environment using workflow in github action configurations
Installed this branch in pace, pyFV3, and pySHiELD to verify that the changes also avoid circular import issues in these modules.
**Checklist:**
> Fixes for circular imports in pyFV3

- ndsl/stencils/basic_operations.py
- tests/test_basic_operations.py
Added basic_operations.py from pyFV3/stencils to ndsl/stencils
Fixes # [18](https://github.com/NOAA-GFDL/NDSL/issues/18)
Tested via lint and currently implemented translate tests
OS: RHEL 8.9 Ootpa
Built conda environment using workflow in github action configurations
**Checklist:**
> Added basic_operations.py from pyFV3/stencils to ndsl/stencils

- ndsl/grid/eta.py
- ndsl/grid/generation.py
- setup.py
In order to facilitate integration with existing model, we allow the pressure coefficients AK/BK to be read from data. We keep the same checks and give precedence to the data to keep backward compatibility.
Tested on GEOS integration. No unit test present but default behavior did _not_ change.
**Checklist:**
> Allow pressure coeff to be read from ak & bk data

- .pre-commit-config.yaml
- ndsl/types.py
`mypy` has been running on an older version (0.812). This updates to `1.4.1` to make sure all py311 new features are being caught.
Running on `pre-commit`
**Checklist:**
> Update to `mypy` 1.4.1

- ndsl/boilerplate.py
- tests/test_boilerplate.py
In order to present an unified, easy and clean API to the user, we start here a series of "boilerplate" code that wrap common use cases. The first of those is the "quick test" with a one tile, no boundaries, no comms, for `numpy ` and `orchestrated dace:cpu`
Adding two boilerplate code
**Checklist:**
> Boilerplate code for fast deploy of NDSL

- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/serialbox_to_netcdf.py
- ndsl/stencils/testing/test_translate.py
- setup.py
The Translate Test needs a lot of love. The first step is to make sure no code lives outside of `ndsl` that should be back to the mothership. This pulls `pyFV3` and `pySHiELD` code that should not be there.
⚠️ `pyFV3` and `pySHiELD` will break and need to be adapted. Namely there `conftest` needs to import `ndsl.conftest`⚠️ 
Other change to allow for an easier "from scratch" experience for testing are:
- `--dperiodic` is removed, replaced with a `--layout` option with `cube` and `tile` as values to describe which grid the test needs
- `--compute_grid` is removed and extended by `--grid` option with `file` (default), `compute` (replaces `--compute_grid` and `default` which allows to run a test with no `Grid-Info.nc` present on a simple `npx/npy/npz` grid with no metric …
> [Refactor] Centralize Translate Test architecture

- ndsl/stencils/testing/translate.py
Part of the mixed precision small details left after the original push. "Parameters" in translate test are not casted to Float using the global precision mechanism, leading to numerical errors for translate check at 32-bit float.
Ongoing port of the microphysics in GEOS
**Checklist:**
> Cast parameters in Translate test to proper float precision

- ndsl/stencils/testing/conftest.py
When building a default Grid, do not pass adjusted npx/npy, as the `_make` function will do it for you.
pyMoist (GEOSmoist physics) is using this feature.
**Checklist:**
> Translate test: "default" grid over-compute the npx/npy parameters

- ndsl/dsl/stencil.py
- ndsl/stencils/corners.py
- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/test_translate.py
Conditional statement in `stencils/testing/test_translate.py` changed to check for `compute` passed via the `--grid` pytest option.
Switched conditional statement in `ndsl/stencils/testing/conftest.py` to check for option of `cubed-sphere` selection
Made `mysign` parameter of `fill_corners_dgrid_defn` an external variable
Resolves Issue [52](https://github.com/NOAA-GFDL/NDSL/issues/52)
Tested in `pyFV3` and `pySHiELD` translate tests github workflow.
**Checklist:**
> Changes to test configurations options and externals for parsing

- .github/workflows/lint.yaml
- .github/workflows/unit_tests.yaml
- setup.py
FIX: Pins `numpy` and `netcdf5` versions to avoid API issues.
Tested in the dependent repositories `pace`, `pyFV3`, and `pySHiELD`.
**Checklist:**
> FIX: Pinning numpy version in setup.py

- ndsl/stencils/corners.py
Regarding fixes to orchestration for unused variables, this change of `mysign` to an external variable is no longer necessary, and so to preserve the original state of the python source this change is being reverted.
Tested via CI triggering translate tests across dependent repositories
**Checklist:**
> Reverting changes to use of mysign in corners.py

- ndsl/stencils/testing/serialbox_to_netcdf.py
The tool to bring Serialbox raw data to netCDF was creating `np.float64` for all fields and scalars. This fix make sure the netCDF reflects the Fortran type as saved
Local generation of dataset at f32 and f64 precision.
**Checklist:**
> Serialbox tool: fix type mismatch

- ndsl/stencils/corners.py
This PR fix the python 3.11 runtime bugs caused by the node visitor transverse depth limitation, it crashed as missing symbol error during runtime. 
This is caused by the optimization pass for oir and dace sdfg, which removes the "unused" symbol, because the limitation of node visitor transver depth limitation. This issue appeared in the dace backend with and without orchestration option.
Fixes # (issue)
This fix has been tested on AMD box using dace backend with and without orchestration option using CPUs.
**Checklist:**
- [ y ] My code follows the style guidelines of this project
- [ y ] I have performed a self-review of my own code
- [ y ] I have commented my code, particularly in hard-to-understand areas
- [ y ] My changes generate no new …
> fix the mysign symbol missing bug in python 3.11

- ndsl/stencils/testing/serialbox_to_netcdf.py
This PR adds an option to merge data into a single savepoint when the Fortran code has been horizontally blocked. Data is reshaped into nx by ny in order to fit directly into the correct quantity size.
This code has been used to postprocess test data for pySHiELD development
**Checklist:**
> Option to merge blocks in serialized data

- ndsl/stencils/testing/translate.py
Previously, boolean namelist parameters were being cast to floats, which passed typechecks because native Python can handle int or float values as bools, but GT4Py does not, which caused problems with non-boolean conditionals inside stencils. This fixes that behavior by preserving boolean parameters in the translate test data.
Fixes # (issue)
If this is a hotfix to a released version, please specify it.
Tested with physics translate tests
**Checklist:**
> hotfix to handle bools in serialized test data

- ndsl/stencils/testing/test_translate.py
- ndsl/testing/comparison.py
In order to enhance reading the errors of a failing translate tests we print on terminal only the first ~10 errors, the full detailed are being saved in a file in the `.translate-errors` alongside the `nc` 
Local test on failing ports.
**Checklist:**
> [QOL] Break report Translate errors in terminal & files

- ndsl/dsl/stencil.py
- tests/dsl/test_stencil_factory.py
The new feature in development to allow absolute indexing in K allows to easily code patterns like "get the top of the column"... as long as you know what top is.
As we have done in the past for I and J, we expose via `__externals__` the bounds of K for the stencil.
This is a zero-cost variable (no cost when not used, no perf cost when used)
Extended utest
**Checklist:**
> [feature] Expose stencil vertical domain to Frozen Stencil

- ndsl/stencils/testing/translate.py
There is a typo in the translate test class that causes crashes with bool test data
Tests don't crash with this fix
**Checklist:**
> Fixing a typo that breaks bools in translate tests

- examples/NDSL/03_orchestration_basics.ipynb
- ndsl/boilerplate.py
- tests/test_boilerplate.py
Very small PR that update the boilerplate calls to a more nimble way that gives the `backend` as a parameter
> Make boilerplate calls more nimble

- ndsl/stencils/testing/savepoint.py
- ndsl/stencils/testing/serialbox_to_netcdf.py
- ndsl/stencils/testing/test_translate.py
We are developing a new capacity of serialbox to append scalars to a one dimension array. This can be used to save data within iterative solver. This means that the number of data point save can vary by rank, so we have developed a solution to collapse all ranks into one to fit with the Translate test system. E.g.:
- Detect when array have different dimensions, if only one dimension, collapse
- Clean up type infer
- Log work being done
Locally
**Checklist:**
> [Serialbox to Netcdf tool] Collapse all rank into 1 if rank have different sized data

- ndsl/dsl/typing.py
- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/test_translate.py
- ndsl/stencils/testing/translate.py
New feature for translate test `--which_savepoint=X` with `X` a number, that allows to run only the given savepoint for a test when there's more than 1
Other QOL:
- better error when output netcdf is missing a required field
- remove return `None` on `Float` which throws mypy/flak8 into a tailspin
- fix a missing type check for regular python `int`
> Ttranslate test `--which_savepoint`

- ndsl/constants.py
Add SECONDS_PER_DAY as a constants following mixed precision standards
Upcoming pyFV3 mixed precision changes of Rayleigh Damping is using this.
> Add SECONDS_PER_DAY as a constant

- ndsl/dsl/dace/orchestration.py
Readability improvements in dace orchestration including
- early returns
- spelling out variable names
- fixing typos
This is part of a tech debt / cleanup series of PRs going into NDSL, gt4py, and dace.
Existing tests in CI will ensure nothing serious is broken by these changes.
**Checklist:**
I guess so ... not sure though. How do people usually check?
> Cleanups in dace orchestration

- ndsl/constants.py
Make sure all constants adhere to the floating point precision set by `Float`
**Checklist:**
> [F32] Constants must default to the system-wide floating point precision

- ndsl/grid/helper.py
- ndsl/stencils/testing/grid.py
Forward all missing SG (cos and sin) from the `MetricTerms` to the `GridData`
GridData is a `dataclass` so any missing argument errors out. This has been running via utest of tracers.
**Checklist:**
> Expose all SG metric terms in `GridData`

- ndsl/grid/generation.py
This PR amends the usage of `MPIComm.allreduce` in `ndsl/grid/generation::MetricTerms._reduce_global_area_minmaxes` to use `ReductionOperator` instances instead of built-in methods.
Tested using the tests currently include in the github workflow. An additional test of a numpy backend c12 baroclinic, 1x1 layout run will be added to the pace workflow as well to ensure future commits do not effect model runs.
**Checklist:**
> Hotfix for grid generation use of mpi operators

- setup.py
This updates the version of netcdf4 to 1.7.1, which fixes install paths we need for our dockerfiles.
docker images have been successfully built after this change
**Checklist:**
> Hotfix to netcdf python version

- ndsl/comm/communicator.py
- ndsl/initialization/sizer.py
This PR is linked to the discussion and investigation linked to [Issue 81](https://github.com/NOAA-GFDL/NDSL/issues/81). For `Quantity` objects with a compute domain containing less than 4 points and exception will be raised when calling `vector_halo_update`.
Tested using the current unit tests available within `NDSL` and the repositories of which it is a submodule.
**Checklist:**
> Adding in exception for compute domains with sizes less than or equal to halo size

- ndsl/grid/generation.py
Fix passing down ak/bk for pressure coefficients when they are available from an outside source (online model case) and given direct to `MetricTerms.__init__`
**Checklist:**
> [Fix] Pressure coefficients from external source

- .github/workflows/lint.yaml
Linting should give fast feedback. The current workflow takes ~3mins where most of the time is spent installing (unnecessary) python packages. To run `pre-commit`, we only need the source files and `pre-commit` itself, which can be installed standalone. This brings runtime of the linting stage down to less than a minute.
Other changes
- update checkout action to v4
- update python setup action to v5
- change python version from 3.11.7 to 3.11 (any patch number will do)
This is a follow-up of PR https://github.com/NOAA-GFDL/PyFV3/pull/40 in PyFV3.
Changed CI workflow is still passing.
**Checklist:**
> [CI] Streamline linting workflow

- ndsl/dsl/typing.py
Type hint was too generic (`type`) leading to `mypy` throwing it's hand in the air and block all PRs (lint failure)
This should push sanity back into the `linter`
Bug reproduced locally, `pre-commit` now passes.
> [FIX] Type hint for precision dependant Float, Int

- ndsl/constants.py
- ndsl/namelist.py
Adds the Stephan-Boltzmann constant to constants, and adds the "daily mean" namelist option for physics to use daily mean radiation values instead of interpolated ones.
PySHiELD tests pass with these changes
**Checklist:**
> Adds some quick capacities used in the post-radiation phase of the physics, including the  Stefan-Boltzmann constant

- ndsl/constants.py
This PR adds the TTP constant to the constants file. I'm putting it in NDSL and not PySHiELD because it shouldn't change between models and is used in a few places.
Calculations using it in PySHiELD pass validation against Fortran
**Checklist:**
> Adding temperature of h2o triple point

- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/savepoint.py
- ndsl/stencils/testing/serialbox_to_netcdf.py
- ndsl/stencils/testing/test_translate.py
- ndsl/stencils/testing/translate.py
- setup.py
A few small tweaks to improve the porting workflow:
- `--no_report` option: doesn't save logs or netcdf when failing translate test.
- Organize fields in error report netcdf by `fail` / `pass` and variable names (sorted).
- Logs moved to a `details` subfolder
- Order variable name in the resulting NetCDF when using `serialbox-to-netcdf`
:warning: Update to `xarray` to make the new netcdf datatree possible :warning: 
**Checklist:**
> [Feature] Porting workflow: enhancing errors readability

- ndsl/monitor/netcdf_monitor.py
This PR enables the precision of data for NetCDF output to be configurable through the `diagnostics_config` section of input config yaml as used by Pace. Precision can be set in the following way:
```
diagnostics_config:
path: output
output_format: netcdf
precision: Float | float32 |float64
```
The `Float` option will use whatever is the current value of the `PACE_FLOAT_PRECISION` environment variable for output precision. 
The `float32` option will set the output precision to be `numpy.float32`. 
The `float64` option will set the output precision to be `numpy.float64`. 
The default option is `Float`. 
The latter two options allow for instances when the desired run precision, as set by `PACE_FLOAT_PRECISION`, will be different than the required output precision. 
If the …
> Feature: NetCDF output precision configurable

- .gitignore
- ndsl/constants.py
- ndsl/stencils/testing/savepoint.py
- ndsl/stencils/testing/translate.py
- ndsl/testing/comparison.py
Mixed precision fixes:
- Translate: read parameters with the correct type, get rid of workaround
- Constants: CNST_OP20 is a true 64-bit 
Quality of Life
- Update `gitignore` to skip `gt4py.next` caches
- MutiModalMetric now doesn't report the expected NaNs
**Checklist:**
> Mixed Precision fixes and QOL

- ndsl/dsl/gt4py_utils.py
- ndsl/grid/generation.py
- ndsl/grid/helper.py
- ndsl/quantity/quantity.py
- ndsl/stencils/testing/grid.py
- ndsl/stencils/testing/translate.py
**Fix Grid for mixed precision code**
- `fC` and `f0` are now loaded from `GridInfo-In.nc`
- Translate test is fixed so it can load 64-bit grid data
- `gt4py_utils` properly forward the `dtype` down to the allocators
**QOL**
- Quantity `data_array` can be switch to full `data`
- Quantity `to_netcdf` can name dataset.
**Checklist:**
> Grid Mixed Precision and Coriolis force load (+ QOL)

- ndsl/stencils/testing/test_translate.py
Small fix to match the new API for netcdf save on reporting for translate tests
> Fix saving NetCDF for parallel translate test

- ndsl/stencils/testing/README.md
- ndsl/stencils/testing/test_translate.py
- ndsl/stencils/testing/translate.py
Currently, when translate tests fail, we run 10 (by default) times the same translate test/savepoint again with slightly perturbed inputs. The outputs are then analyzed to give developers an indication on whether errors that they are seeing are in the expected range of "noise propagation" or if this is more likely to be an error in porting.
This goes back to https://github.com/ai2cm/pace/pull/222, which was never finished. Issue https://github.com/NOAA-GFDL/NDSL/issues/133 was created to re-evaluate that system.
Tested locally by setting the environment variable to 0.
**Checklist:**
> Translate tests: no threshold analysis by default

- ndsl/dsl/typing.py
Remove deprecated function as discussed in https://github.com/NOAA-GFDL/PyFV3/pull/54#issuecomment-2866552075. The function was replaced with `get_precision()` in 2025.03.00.
Fixed (upstream) PyFV3 in https://github.com/NOAA-GFDL/PyFV3/pull/54. Found no occurrences in pace and PySHiELD. Updated [NDSL](https://github.com/NOAA-GFDL/pace/pull/120) & [PyFV3](https://github.com/NOAA-GFDL/pace/pull/121) versions of pace.
**Checklist:**
> Remove deprecated `floating_point_precision()`

- ndsl/dsl/gt4py/__init__.py
We forgot to expose `stencil` from `GT4Py` in the new interface.
Will be covered by pace tests once https://github.com/NOAA-GFDL/pace/pull/114 is merged.
**Checklist:**
> Expose stencil from gt4py

- ndsl/__init__.py
- ndsl/dsl/stencil.py
- ndsl/quantity/__init__.py
- ndsl/quantity/field_bundle.py
- tests/quantity/test_fieldbundle.py
- Boilerplate code taking in a 4D Quantity
- Name/Index indexer
- Natively orchastreatable 
- Deferred type hint for data dimensions
- Unit tests
New units tests for basic usage
**Checklist:**
> Field Bundle: Functional code for 4D array

- ndsl/grid/generation.py
- ndsl/grid/helper.py
Small changes coming from Dynamics up-skill to mixed precision
- Make `area64` available for 32-bit or mixed code versions
- Make `ptop` available to GPU for orchestration (by properly de-ferencing `cupy` memory)
Ongoing work for pyFV3
**Checklist:**
> Grid metrics terms: mixed precision & GPU readiness

- ndsl/io.py
NDSL tests were logging the following deprecation warning for using `use_cftime=True` when opening a dataset (e.g. model state)
```none
tests/test_legacy_restart.py::test_read_state_non_scalar_time
/__w/NDSL/NDSL/ndsl/io.py:72: DeprecationWarning: Usage of 'use_cftime' as a kwarg is deprecated. Please pass a 'CFDatetimeCoder' instance initialized with 'use_cftime' to the 'decode_times' kwarg instead.
Example usage:
time_coder = xr.coders.CFDatetimeCoder(use_cftime=True)
ds = xr.open_dataset(decode_times=time_coder)
ds = xr.open_dataset(f, use_cftime=True)
```
(as see in e.g. [this run](https://github.com/NOAA-GFDL/NDSL/actions/runs/15280269813/job/42977231218#step:6:784))
By running tests and confirming that the warning isn't in the logs …
> Fix deprecation warning when reading model state

- ndsl/buffer.py
- ndsl/checkpointer/snapshots.py
- ndsl/checkpointer/thresholds.py
- ndsl/comm/caching_comm.py
- ndsl/comm/comm_abc.py
- ndsl/comm/communicator.py
- ndsl/comm/mpi.py
- ndsl/dsl/dace/build.py
- ndsl/dsl/dace/dace_config.py
- ndsl/dsl/dace/orchestration.py
- ndsl/dsl/stencil.py
- ndsl/grid/generation.py
- ndsl/grid/helper.py
- ndsl/halo/data_transformer.py
- ndsl/halo/updater.py
- ndsl/quantity/quantity.py
- ndsl/stencils/testing/grid.py
- ndsl/stencils/testing/translate.py
- tests/test_zarr_monitor.py
The future is here. We don't have to rely on stringified type hints anymore. Instead, we can use `from __future__ import annotations` to have python parse the code twice (once to register all types and then another time to actually check). 
All good as long as CI is still green.
**Checklist:**
> refactor: avoid stringified type hints

- ndsl/stencils/testing/serialbox_to_netcdf.py
We continue to evolve the tool to move serialbox data into netcdf, by allowing non-zero ranks to not have data for certain variables. We copy NaN in place.
> [Serialbox to NetCDF] Allow variables to not be saved in non zero ranks

- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/test_translate.py
- tests/dsl/test_caches.py
- tests/dsl/test_compilation_config.py
- tests/dsl/test_dace_config.py
- tests/dsl/test_skip_passes.py
- tests/dsl/test_stencil.py
- tests/dsl/test_stencil_config.py
- tests/dsl/test_stencil_factory.py
- tests/dsl/test_stencil_wrapper.py
- tests/dsl/utils.py
- tests/mpi/test_mpi_all_reduce_sum.py
- tests/mpi/test_mpi_halo_update.py
- tests/mpi/test_mpi_mock.py
- tests/test_decomposition.py
This PR looks at tests under `tests/dsl` and does some cleanup work. In particular
- Re-enable tests in `tests_caches.py`: They were skipped because `MPI` is always defined (since it's a non-optional import)
- Fix tests in `tests_caches.py`: Tests haven't been running since we moved away from python 3.8 (because the python version was hard-coded in there ...)
- Move `make_storage` into a utility module (used from two test modules)
- Run tests in `tests/dsl/test_stencil_factory.py` with more than one backend
- Adding type hints and "inlining" single parameter sets.
Just to disambiguate: Some tests (the ones inside `tests/mpi`) rely on `MPI` being changed to `None` in case of a serial run:
https://github.com/NOAA-GFDL/NDSL/blob/2986b450386b5006d847f246ff6e8b23abdc9190/tests/m …
> tests: re-enable caching tests and more cleanups in tests/dsl

- .github/workflows/unit_tests.yaml
- setup.py
The current work to run at scale on Grace Hopper unified silicon ARM64 hardware as showcased the need to move `mpi4py` above 4x.
The original restriction to `3.1.5` was done out of an abundance of caution in a moment where halo exchange  were questioned.
Alas, the new allocator that ships with cuda 12.5 for GH boxes especially trips the old `mpi4py`. We need to move up.
The risk is limited as `4.1` showcase a very large amount of fixes to main version 4.
> Upgrade `mpi4py` to >4 

- ndsl/stencils/testing/test_translate.py
- ndsl/testing/README.md
Use full keyword "absolute_epsilon", update docs.
> [Fix] Multimodal override fix for Absolute Epsilon

- docs/porting/translate/index.md
- ndsl/stencils/testing/test_translate.py
A few minor changes to test_translate.py:
- Introduction of a new feature to override the default in/out netcdf names. Use: `self.override_input_netcdf_name = "FILE_NAME"` and `self.override_output_netcdf_name = "FILE_NAME"`. The new file must me in the same folder as the default file.
- Added a new error to prevent accidental overwrites of `self.outputs`, which the translate test infrastructure expects to be unassigned.
> Minor QOL changes to translate test infrastructure

- ndsl/dsl/dace/orchestration.py
- ndsl/dsl/stencil.py
- tests/dsl/test_stencil_wrapper.py
Add support for fields with data_dims (or data_dims only fields) in the stencil wrapper's function to compute field origins.
This PR is work that's being propagated back from the [nasa/milestone2 branch](https://github.com/NOAA-GFDL/NDSL/pull/189).
Added new unit test. Tested locally with bigger reproducer (GFDL_1M orchestration). 
**Checklist:**
> fix: stencil wrapper field origins with data_dims

- ndsl/comm/communicator.py
We've seen issues with large-scale runs on the GPU cluster. Runs would be stuck in the global sum calculation. Putting a `device_synchronize()` in the MPI in-place all_reduce calls seems fix these issues and let's runs finish.
Note that device_synchronization is Cupy/Cuda specific at the moment.
This PR is work that's being propagated back from the [nasa/milestone2 branch](https://github.com/NOAA-GFDL/NDSL/pull/189).
@gmao-ckung was running tests on the GPU cluster.
**Checklist:**
> fix: gpu/mpi synchronization issue with in-place all reduce sum

- ndsl/dsl/dace/dace_config.py
Follow-up from PR #213. Further tests discovered that the the neoverse chips are too new to with `-march=native` and GCC 14. We thus result to `armv8-a`, a more general arm instruction set that is available with GCC 14.
@FlorianDeconinck what do you think? Is this too narrow for our current use-cases? I.e. should we try to detect the GCC version too?
Includes a couple of (unrelated) cleanups 
With @gmao-ckung, we did tests with a copy stencil and a couple of options on the GH box.
> fix: compile flags for GCC (14) on GH200

- ndsl/grid/generation.py
We had a custom decorator for cached properties in grid generation. Since python 3.8 we can just use the one provided by `functools`.
This just replaces a custom decorator with a library call. Regressions are assumed to be covered by existing tests.
> refactor: use modern python for cached properties

- ndsl/grid/generation.py
- ndsl/initialization/allocator.py
This PR fully types `ndsl/initialization/allocator.py` and fixes fallout in the grid generation because `ks` and `ptop` are supposed to be scalars.
This is the clean version of the second part of PR #222.
`mypy` is happy now :upside_down_face:
> fix: fully type allocator and fix fallout

- ndsl/boilerplate.py
- tests/test_boilerplate.py
`ndsl/boilerplate.py` has two functions to simplify creation of `StencilFactory` and `QuantityFactory`. Both factories depend on the backend where the numpy backend acts a fallback for both. The backend wasn't properly forwarded to the `QuantityFactory` leading to data that wasn't necessarily optimally aligned (except e.g. for the numpy backend). For example, in case of the `dace:cpu` backend, this leads to performance warning messages about improperly aligned memory.
This is what Christopher Harrop was seeing because he specified the `dace:cpu` backend in `get_factories_single_tile()`, which wasn't properly forwarded to the `QuantityFactory` leading to warning messages about improperly aligned memory.
This is the clean version of #222, which got a bit out of hands with the cleanups. This …
> fix: boilerplate allocation and layout warnings

- ndsl/initialization/allocator.py
- tests/initialization/test_allocator.py
- tests/test_dimension_sizer.py
The constructor of `QuantityFactory` is scheduled to change after the next release. See https://github.com/NOAA-GFDL/NDSL/pull/228 for context. To give our users a heads-up, let's merge a deprecation warning now.
New tests have been added.
No, but that's kind of the point here.
> Deprecation warning for QuantityFactory constructor

- ndsl/__init__.py
- ndsl/dsl/dace/build.py
- ndsl/dsl/dace/dace_config.py
- ndsl/dsl/dace/orchestration.py
- ndsl/dsl/stencil.py
- tests/dsl/orchestration/test_call.py
The `FrozenCompiledSDFG` was created to cache in the C pointers of the data with an eye of getting the most speed for online code into larger Fortran models. This creates a hidden (nearly undocumented) behavior in which swapping memory (by reallocation or else) is prohibited and will result in wrong answers.
We revert to the previous behavior which is safe (but slow) and test properly for future optimization.
Side quest: we fix the (rare) case where orchestration doesn't touch any `stencils`, where the `dace` build folder set in the frozen stencil call is not enough. Documented the lackluster system in code.
> Remove `FrozenCompiledSDFG` to avert the hidden behavior on orchestration call

- ndsl/dsl/dace/dace_config.py
GT4Py as a flag `GT4PY_COMPILE_OPT_LEVEL` that directs `-O` compiler flags. We have tied it in to the compilation level for DaCe within their CMake system. But we haven't tied it fully and this PR fixes that.
In a subsequent PR we should introduce a NDSL level configuration for optimization that drives both the GT4Py and DaCe sub-configuration.
> [Fix] DaCe build system should be tied more closely to existing configuration

- ndsl/stencils/testing/conftest.py
- ndsl/stencils/testing/parallel_translate.py
- ndsl/stencils/testing/savepoint.py
- ndsl/utils.py
Partial work addressing issue #64  
Adding helper functions for loading `f90nml.Namelist` from file and converting to dict.
There is a slight complication with the translate tests. We need to be able to turn on and off the usage of `ndsl.Namelists`. So, I'm proposing a new temporary flag `--no_legacy_namelist` in `conftest.py` to toggle between two options in the tests:
1. Use only f90nml.Namelist (Long-term desired goal) within the translate tests
2. Continue using f90nml.Namelist and the soon-to-be legacy ndsl.Namelist (Interim solution to facilitate checking in changes one submodule at a time)
Also, I'm modifying ParallelTranslate's layout() to rely more on f90nml.Namelist or ndsl.Namelist temporarily as we work on this issue.
These changes will facilitate the eventual removal of …
> Namelist Refactor: Utility functions for namelist to dict + conftest --no_legacy_namelist

- ndsl/units.py
- tests/test_utils.py
The functions are all unused (I've checked pyFV3, pySHiELD, and pace) and should be removed to keep API surface as small as possible. In the future we envision NDSL to come with much more potent type checking for units. Until then, if really needed, these functions can be implemented trivially by dsl users.
This PR is to be seen in preparation for and context of issue https://github.com/NOAA-GFDL/NDSL/issues/243, which proposes a bigger cleanup in the directory structure of this package. If we can get rid of some deprecated API first, transition will be easier.
Added tests to ensure call to `UnitsError` and the functions exposed in `ndsl/units.py` are deprecated.
No, but that's kind of the point of adding `DeprecationWarnings` ;)
> API cleanup: deprecate `ndsl/units.py`
